---
version: 2

references:
  docker_golang: &docker_golang
    docker:
      - image: golang:1.14.5
    working_directory: /go/src/github.com/gocardless/slo-builder

jobs:
  promtool:
    <<: *docker_golang
    steps:
      - checkout
      - run:
          name: promtool check rules
          command: |
            curl --connect-timeout 15 --retry 3 -sfL \
              https://github.com/prometheus/prometheus/releases/download/v2.20.1/prometheus-2.20.1.linux-amd64.tar.gz \
              | tar --strip-components=1 -xzf - prometheus-2.20.1.linux-amd64/promtool
            ./promtool check rules *-rules.yaml

workflows:
  version: 2
  pipeline:
    jobs:
      - promtool
